language: rust
dist: bionic
sudo: false

cache:
  cargo: true
  apt: true

git:
  depth: 1
  submodules: false

if: 'branch IN (master, test-travis, staging, trying) OR fork = true OR tag =~ ^v'

addons:
  apt:
    packages:
    - gcc
    - librocksdb5.8
    - librocksdb-dev

matrix:
  include:
  - rust: nightly

install: make test
script: cargo build

env:
  global:
    - RUST_BACKTRACE=full
    - USE_SYS_ROCKSDB: true
    - FMT: true
    - CHECK: true
    - TEST: true

before_cache:
  - rm -rf ./target/debug/incremental/
  - cargo sweep -f

deploy:
  provider: releases
  file_glob: true
  file: ./target/release/huobi-chain
  skip_cleanup: true
  on:
    branch: test-travis  # i guess we do need this after all?
  api_key: "$GITHUB_TOKEN"