language: rust
rust: nightly
dist: bionic
sudo: true

env:
  global:
    - RUST_BACKTRACE=full
    - USE_SYS_ROCKSDB: true
    - FMT: true
    - CHECK: true
    - TEST: true

before_cache:
  - rm -rf ./target/debug/incremental/

cache:
  apt: true
  directories:
    - $TRAVIS_HOME/.cargo/

git:
  depth: 2
  submodules: false

if: branch IN (master, test-travis) OR fork = true OR tag =~ ^v

addons:
  apt:
    packages:
    - gcc
    - librocksdb5.8
    - librocksdb-dev

# install: ./devtools/ci/install.sh
# script: ./devtools/ci/script.sh

install: echo "skip install"
script: echo "skip script"

matrix:
  include:
    - name: do ci
      if: 'tag IS NOT present'
    - name: linux package
      if: 'tag IS present'
      os: linux
      script: 
        - cargo build --release
        - ./devtools/ci/package.sh
    - name: osx package
      if: 'tag IS present'
      os: osx
      script: 
        - cargo build --release
        - ./devtools/ci/package.sh
    - name: windows package
      if: 'tag IS present'
      os: windows
      script: 
        - choco install yasm
        - choco install llvm
        - cargo build --release
        - ./devtools/ci/package.sh

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: YFFf2fCiZOKXa2cvS0LUjQexHna9wsIdVfWemfyn4M8fBpTVQpGEFZnlveHhqVFDXpBakm69PEh1ARbpmRQKgvuVDSF0x93U8BZPgVFasrek2PWxlEsN1Oy70hol4i5Nf6tO7xIx6QVueqk7r5wV0fB97C8fxM6EnQOY1NYphXw4uUhC2fH6ZF5wwF3V88EZu+3FcgO5VLEl15AJZ3aXN9QKpmaZ57fRqHXBVbTNXYbvPxwjg7E3qJfgPvyko5mfaFigJx3CvMdpUGWpo6mQtFwuKZbDuaKjEsvGYUALxZvp4bVI5jCD5GpIsweuO+MqazX/2plzHGHkh3SrwO7c/7PuUmOQ1FTv2bh2WeX9v6h8AVJCLRsdJTgBD+SQfWbDLCmHpAFOXikL5uCR+o7txeZbO7OQuL/axQGr/rhAKQQTyUxKKDO3Gs1pHuL3FLyaKkKNJBIQ7o4BfqvjIvUdPHsdhN8KhCcaczHGfjGJ64CmpHDTdHQAyYF9kRAwXOn7EuE/k5M2FvbIthDFybjrWi35pzskJPxfwSRuDXUieIBKfJorrIPSPpDBmaOF2YFv2NWquz3/LwBgG7AQyxoBd0r5xqCt9GfxQDnKoAbEYysyy1ZTJgSsx/96gdan8+9KSyPOAmgUMgHoRxzLWsYrxl4T4ql3aB8laoq9OSDi8hI=
  file:
    - huobi-chain-$TRAVIS_TAG-linux.tar.gz
    - huobi-chain-$TRAVIS_TAG-osx.tar.gz
    - huobi-chain-$TRAVIS_TAG-windows.zip
  on:
    repo: mkxbl/huobi-chain
    tags: true
